#!/usr/bin/env bash
# shellcheck disable=2093
#set -x
#set -u
shopt -s extglob
shopt -s nullglob
shopt -s nocasematch
:
function cleanup {
    printf '\n\n\e[7m%s\e[0m\n\n' $'I'\''ll be seeing you.'
    printf 'Cleaning up ... '
    kill %1 >/dev/null 2>&1
    wait
    (sleep 20
     if hard_check "${daemon}"
     then
         slay "${daemon}" >/dev/null 2>&1
     fi
    ) &
    disown %1
    jobs
    printf 'done.\n\n'

    [[ "${#daemon}" -gt 0 ]] && \
        printf 'Note: The daemon \e[91m%s=\e[0m may have materialized despite interruption.\n' "${daemon^^}" && \
        printf "Attempting to slay in the background.\\n\\n" && \
        printf 'Enter %s to be sure.\n' $'`baphomet -l`'
    exit
}
trap cleanup TERM INT SIGINT SIGTERM
:
case ${@:1:1} in
    -x|--escape)
        exec command emacs "${@:2}"
        ;;
    -Q|--quick)
        exec command emacs -Q "${@:2}"
        ;;
esac
# # # # #
# U T I L
# # # # #
containsElement () {
    local e match="$1"
    shift
    for e; do [[ "$e" == "$match" ]] && return 0; done
    return 1
}

userTest () {
    [[ ${#@} -ne 0 ]] && USER="${1}"
    :
    id -u "${USER}" >/dev/null 2>&1
    if [[ $? -eq 1 ]]; then
        printf 'The user %s is not known to exist.\n' "${USER^^}"; return 1
    fi
    return 0
}
:
EMACS_SOCKET_DIR="/tmp/baphomet/${USER}/"
[[ ! -d $EMACS_SOCKET_DIR  ]] && mkdir -p "${EMACS_SOCKET_DIR}"


DAEMON_SPLASH=$'(progn (defconst baphomet-buffer "*BAPHOMET WELCOMES YOU*")
(with-current-buffer (get-buffer-create baphomet-buffer))
(switch-to-buffer baphomet-buffer) (setq header-line-format "BAPHOMET"))'

#LISP_FRAME_CHECK=$'(if (> (length (frame-list)) 1) '"'"'t)'
:
LISP_BUFFER_COUNT=$'(length (cl-remove-if-not '"'"'buffer-file-name (buffer-list)))'
:
LISP_BUFFER_LIST=$'(concat (daemonp) ";" (mapconcat '"'"'identity (delete '"'"'nil (mapcar '"'"'buffer-file-name (buffer-list))) "+++"))'
:
LISP_PID=$'(emacs-pid)'
:
:

hard_check () {
    local socket="${EMACS_SOCKET_DIR}/${1}"
    [[ -S $socket ]] && return 0
    :
    return 1
}

list_sockets () {
    local socket
    local daemon
    :
    arrSockets=("${EMACS_SOCKET_DIR}"/*)
    arrDaemons=()
    :
    for socket in "${arrSockets[@]}"
    do
        if [[ -S $socket ]]; then
            arrDaemons+=("$(basename "${socket^^}")")
        fi
    done
    pd=("${arrDaemons[@]//\!/\/}")
    pd=("${pd[@]/%/=}")
}
# generate sockets array
list_sockets

pretty () {
    # make it presentable
    ## takes a reference
    x="${!1//\!/\/}"
    x="${x/%/=}"
    eval "${1}=${x}"
}


query_daemon () {
    unset result
    local element
    local CMD="${1}"
    :
    for s in "${arrSockets[@]}"
    do
        read -r element < <(nc -U "${s}" <<< \
                               $"-eval ${CMD// /&_}" | \
                                awk $'FNR == 2 {printf $2}')
        result+=("${element}")
    done
}

message_daemon () {
    unset CMD
    local CMD="${1}"
    if [[ "${#2}" -gt 0 ]]; then
        nc -U "${2}" <<< \
           $"-eval ${CMD// /&_}"
    fi
}

slay () {
    local socket
    socket="${EMACS_SOCKET_DIR}/$(basename "${1}")"
    nc -U "${socket}" <<< '-eval (kill-emacs)' >/dev/null 2>&1 &
    printf 'Slaying daemon known as \e[33m%s=\e[0m ...' "$(basename "${socket^^}")"
    wait
    printf ' done.\n'
    printf ' So slain.\n'
}

sanitize () {
    unset result
    :
    result="${1//[^a-zA-Z0-9\/]/}"
    result="${result////!}"
    result="${result%!}"
    result="${result#!}"
}


msg () {
    printf '\e[7m\n\n%s' $' \u2605 '
    if [[ $1 -eq 201 ]]; then
        printf 'Summoning the daemon \b%b ...' ${2:+" \\e[31m${2^^}=\\e[m\\e[7m"}
        wait "${3}"
        printf ' done. \n'
        printf 'So summoned.\n'
    elif [[ $1 -eq 204 ]]; then
        printf '%s' $'May you live long and prosper.'
    elif [[ $1 -eq 400 ]]; then
        printf '\e[31mBad choice.\e[0m\n'
    elif [[ $1 -eq 404 ]]; then
        printf 'The daemon \b%b was not found!\n' ${2:+" \\e[31m${2^^}=\\e[m\\e[7m"}
    elif [[ $1 -eq 0404 ]]; then
        printf '%s' $'No daemons to be found.'
    fi
    printf '\e[0m\n\n'
}

while [[ ${#@} -ne 0 ]]
do
    case $1 in
        -i|--interactive|-is|--shell)
            break  3
            ;;
        -u|--user)
            UZR="${2}"
            [[ ${#UZR} -eq 0 ]] && \
                printf 'A user must be specified!\n' && exit 1
            if ! userTest "${UZR}"; then exit 1; fi
            :
            shift 2
            USER="${UZR}" exec "${0}" "${@}"
            ;;
        --join|-j)
            B_STATE="JOIN"
            :
            daemon="${2}"
            if [[ ${#daemon} -eq 0 ]]; then
                [[ "${#arrSockets[@]}" -eq 0 ]] && msg 0404 && exit
                printf '\e[33m%.0s-' {1..20}; echo
                printf '     DAEMON MENU\n'
                printf '%.0s-' {1..20};  printf '\e[0m\n\n'
                printf '\e[37;4;2m%s\e[0m\n' "${EMACS_SOCKET_DIR}"

                select daemon in "${arrDaemons[@]}" ${OFFER:+"Commune with $OFFER="} "Quit"
                do
                    [[ "${daemon^^}" == "QUIT"  ]] && \
                        msg 204 && \
                        exit 0
                    :
                    if [[ $INTERACTIVE == TRUE ]]
                    then
                        printf '\n\e[31mName a buffer or file by absolute path\e[0m: '
                        read -r EMACS_BUFFER_NAME
                        break
                    fi
                    exec "${0}" -j "${daemon}"
                done
            fi
            :
            socket="${EMACS_SOCKET_DIR}/${daemon}"
            if containsElement "${socket}" "${arrSockets[@]}"
            then
                :
                shift 2
                continue
            else
                msg 404 "${daemon}"
                shift 2
                OFFER="${daemon}"
                exec "${0}" --list
            fi
            exit
            ;;
        --list|--list-daemons|-l|-ls)
            printf '\e[37;4;2m%s\e[0m\n\n' "${EMACS_SOCKET_DIR}"
            printf '\e[33m%s\e[0m\n' $'\e[37;4;2mDaemons\e[0m' "${pd[@]:-No daemons found.}"
            if  [[ $INTERACTIVE == TRUE ]]; then
                printf '\n\n\e[31mWhat do you desire?\e[0m\n'
                select option in 'Return' 'Quit'
                do
                    case $option in
                        'Return')
                            exec "${0}" -i
                            ;;
                        'Quit')
                            exit
                            ;;
                    esac
                done
            fi
            exit
            ;;
        --list-very-verbose|-lvv)
            query_daemon "${LISP_BUFFER_COUNT}"; arrBuffers=("${result[@]}")
            query_daemon "${LISP_PID}"; arr_pids=("${result[@]}")
            :
            printf '\e[37;4;2m%s\e[0m\n\n' "${EMACS_SOCKET_DIR}"
            paste <(printf '\e[33m%s\e[0m\n' $'Daemons' "${pd[@]:- none}") <(printf '%s\n' $'Files #' "${arrBuffers[@]:- –}") <(printf '%s\n' $'PID' "${arr_pids[@]:- –}") |sed $'s/\t/,|,/g' |  column -s ',' -t
            :
            exit
            ;;
        --list-verbose|-lv)
            query_daemon "${LISP_BUFFER_COUNT}"; arrBuffers=("${result[@]}")
            :
            printf '\e[37;4;2m%s\e[0m\n\n' "${EMACS_SOCKET_DIR}"
            paste <(printf '\e[33m%s\e[0m\n' $'Daemons' "${pd[@]:- None found}") <(printf '%s\n' $'Files #' "${arrBuffers[@]- –}") |sed $'s/\t/,|,/g' |  column -s ',' -t
            exit
            ;;
        --list-buffers|-lb)
            query_daemon "${LISP_BUFFER_LIST}"
	    printf '\e[37;4;2m%-20s\e[0m\n' "File buffers"
            R="${result[0]//$'+++'/$'\n'}"
            R="${R//\"/}"
	    #            paste  <(printf '%s' "${R}")
	    printf '%s\n' "${R}"|tr ';' '\n'
            exit
            ;;
        --kill-all|-ka)
            DIE="DIE"
            ;&
        --stop|--kill|-k)
            :
            printf '\e[37;4;2m%s\e[0m\n' "${EMACS_SOCKET_DIR}"
            [[ "${#arrSockets[@]}" -eq 0 ]] && \
                msg 0404  && exit
            :
            if [[ $DIE == "DIE" ]]; then
                for socket in "${arrSockets[@]}"
                do
                    slay "${socket}"
                done
                exit
            fi
            :
            daemon="${2}"
            socket="${EMACS_SOCKET_DIR}/${daemon}"
            if [[ ${#daemon} -eq 0 ]]
            then
                printf "Choose a daemon to slay:\\n" && \
                    select daemon in "${arrDaemons[@]}"
                    do
                        daemon="${daemon//=/}"
                        socket="${EMACS_SOCKET_DIR}/${daemon}"
                        slay "${socket}"

                        exit
                    done
            else
                containsElement "${socket}" "${arrSockets[@]}"
                if [[ $? -eq 1 ]]; then
                    msg 404 "${daemon}"
                else
                    slay "${socket}"
                fi
                exit
            fi
            :
            exit
            ;;
        --file|-f|--buffer|-b)
            if [[ ${#2} -eq 0 ]]; then
                printf 'No file or buffer specified!\n';exit
            else
                EMACS_BUFFER_NAME="${2}"
            fi
            ;;
        --start|--summon|-c|-s)
            IFS=,
            daemons="${2}"
            :
            if [[ ${#daemons} -eq 0 ]]; then
                if [[ ${#arrDaemons[*]} -eq 0 ]]; then
                    daemons="server"
                else
                    daemons="${arrDaemons[0]}"
                fi
            fi
            :
            for daemon in $daemons; do
                :
                sanitize "${daemon}"
                daemon="${result}"
                socket="${EMACS_SOCKET_DIR}/${daemon}"
                if containsElement "${socket}" "${arrSockets[@]}"
                then
                    exec "${0}" -j "${daemon}" "${@:3}"
                else
                    \emacs --eval "${DAEMON_SPLASH}" --user="${USER}" --daemon="${socket}" > /dev/null 2>&1 &
                    msg 201 "${daemon^^}" '%1'
                    :
                    if containsElement '--' "${@}"
                    then
                        EMACS_BUFFER_NAME="${@}"
                        EMACS_BUFFER_NAME="${EMACS_BUFFER_NAME#*\ \-\-\ }"
                        [[ "${#EMACS_BUFFER_NAME}" -gt 0 ]] && \
                        EMACS_BUFFER_NAME="${EMACS_BUFFER_NAME}" exec "${0}" -j "${daemon}"
                    fi
                fi
            done
            exit
            ;;
        --debug|-d)
            printf 'Debug mode not ready!\n'
            exit
            ;;
        -w|--watch)
            printf 'Watch all daemonic activity.\n'
            exit
            ;;
        -z)
            # (mapconcat 'identity (delete 'nil (mapcar 'buffer-file-name (buffer-list))) "+++")
            query_daemon "${LISP_BUFFER_LIST}"
            printf "${result[0]}";exit
            r="${result[@]//[^a-zA-Z0-9\/\&\_]/}"
            printf '%s' "${r}"
            exit
            ;;
        --)
            EMACS_BUFFER_NAME="${2}"
            shift
            break 3
            ;;
        --help|-h)
            printf "\\x1b[38;2;250;0;0m%s\\x1b[0m\\n" \
                   "BAPHOMET -- manage your emacs daemons"
            printf "\\x1b[38;2;100;100;100m"
            cat <<'EOF'
   Usage: baphomet [switches] [arguments]
   -h,  --help                      Display (this) help menu
   -s,  --start [name[,name2]]      Start one or more daemons,
   comma separated
   -k,  --kill, --stop [name]       Stop a daemon with name 'name'
   -ka, --kill-all                  Stop all daemons
   -j,  --join [name]               Join a daemon with name 'name'
   -l,  --list                      List known daemons
   -lv, --list-verbose              List daemons and file buffer count
   -lvv, --list-very-verbose        List daemons and file buffer count
   and daemon PID

   -i,  --interactive               Interactive mode
   --shell                          Interactive shell mode
   -x,  --escape                    Exit script, run emacs as normal


   Note:
   When called without arguments, baphomet starts a new daemon
   if necessary and opens a buffer with a default name.
   When called with only a buffer or filename, baphomet joins any daemon
   and creates buffer with specified name.

   Examples with a daemon named 'joey'
   start daemon: baphomet --start joey
   stop daemon:  baphomet --stop joey
   join daemon:  baphomet --join joey

   Disclaimer: Execute this script at your own peril.
EOF

            printf "\\x1b[0m"
            exit
            ;;
        -*)
            printf '\e[31mUnknown argument "%s"\e[0m\n\v' "${1}"
            exit 1
            ;;
        *)
            break;
            ;;
    esac
    [[ "${#@}" -gt 0 ]] && shift 2
done
:
if [[ ${B_STATE} == "JOIN" ]]; then
    exec emacsclient -q -c -s "${socket}" -- ${EMACS_BUFFER_NAME:+"$EMACS_BUFFER_NAME"}
fi


case ${@:1:1} in
    -i|--interactive)
        printf '\e[33m%.0s-' {1..20}; printf '\n'
        printf '     MAIN MENU\n'
        printf '%.0s-' {1..20};  printf '\e[0m\n'
        select option in ${arrDaemons[@]:+'List'} ${arrDaemons[@]:+$'Join'} ${arrDaemons[@]:+$'Slay'} $'Summon' $'Shell' $'Quit'
        do
            option=$(printf '%s' "${option}" |perl -pe 's/\x1b\[[0-9;]*[mG]//g')
            :
            case $option in
                'List')
                    INTERACTIVE=TRUE exec "${0}" -l
                    ;;
                'Join')
                    INTERACTIVE=TRUE exec "${0}" -j
                    ;;
                'Slay')
                    INTERACTIVE=TRUE exec "${0}" -k
                    ;;
                'Summon')
                    printf '\n\e[31mName your daemon\e[0m: '
                    read -r daemon
                    [[ "${daemon^^}" == "BAPHOMET" ]] && printf 'No.\n' && exit 1
                    INTERACTIVE=TRUE exec "${0}" -s "${daemon}"
                    ;;
                'Shell')
                    INTERACTIVE=TRUE exec "${0}" --shell
                    ;;
                'Quit')
                    msg 204
                    exit
                    ;;
                *)
                    msg 400
                    ;;
            esac
        done
        ;;
esac



case ${@:1:1} in
    --shell|-is)
        exec bash --rcfile <(read -r baphomet_shell < \
                                  <(printf '%s' "PS1=$'\\e[38;5;196m\\u2605 BAPHOMET >\\e[0m ' ;\
                                       trap \"printf '%s\\n\\n' $'\\111\\47\\154\\154\\40 \\142\\145\\40 \\163\\145\\145\\151\\156\\147\\40 \\171\\157\\165\\56'; tput clear \"  EXIT;\
                                       cd $EMACS_SOCKET_DIR;\
                                       tput clear;\
                                       read -r rows cols < <( stty size );\
                                       cols=\"\$(( \$cols - 20 ))\";\
                                       tput sc ; tput cup \$rows \$cols ; echo \"As above, so below\" ; tput rc;\
                                       alias ls=\"ls -lF\";\
                                       alias help=\"${0} -h\";\
                                       alias list=\"${0} -l\";\
                                       alias lv=\"${0} -lv\";\
                                       alias lvv=\"${0} -lvv\";\
                                       alias start=\"${0} -s\";\
                                       alias summon=start;\
                                       alias kill=\"${0} -k\";\
                                       alias kill-all=\"${0} -ka\";\
                                       alias ka=kill-all;\
                                       alias join=\"${0} -j\";\
                                       "); printf '%s' "${baphomet_shell}") -i
        ;;
esac

socket="${arrSockets[0]}"
daemon="$(basename "${socket}")"
[[ ${#socket} -gt 0 ]] && \
    EMACS_BUFFER_NAME=${1:-'*BAPHOMET WELCOMES YOU*'} exec "${0}" -j "${daemon}"

printf '\e[0;36m%s\e[0m\n' "No daemons found. Let's get interactive."
exec "${0}" --interactive
